export const moviesDummyData = [
  {
    name: 'The Godfather',
    genre: ['Crime', 'Drama'],
    director: 'Francis Ford Coppola',
    cast: ['Marlon Brando', 'Al Pacino', 'James Caan'],
    setting: 'New York City, 1940s-50s',
    plot: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
  },
  {
    name: 'Titanic',
    genre: ['Drama', 'Romance'],
    director: 'James Cameron',
    cast: ['Leonardo DiCaprio', 'Kate Winslet', 'Billy Zane'],
    setting: 'Atlantic Ocean, 1912',
    plot: 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.',
  },
  {
    name: 'The Shawshank Redemption',
    genre: ['Drama'],
    director: 'Frank Darabont',
    cast: ['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'],
    setting: 'Shawshank State Penitentiary, 1940s-60s',
    plot: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
  },
  {
    name: 'The Dark Knight',
    genre: ['Action', 'Crime', 'Drama'],
    director: 'Christopher Nolan',
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
    setting: 'Gotham City',
    plot: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
  },
  {
    name: 'Forrest Gump',
    genre: ['Drama', 'Romance'],
    director: 'Robert Zemeckis',
    cast: ['Tom Hanks', 'Robin Wright', 'Gary Sinise'],
    setting: 'United States, 1950s-80s',
    plot: 'The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold from the perspective of an Alabama man with an IQ of 75.',
  },
  {
    name: 'Inception',
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    director: 'Christopher Nolan',
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Ellen Page'],
    setting: 'Dream world',
    plot: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
  },
  {
    name: 'Pulp Fiction',
    genre: ['Crime', 'Drama'],
    director: 'Quentin Tarantino',
    cast: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'],
    setting: 'Los Angeles',
    plot: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
  },
  {
    name: 'The Matrix',
    genre: ['Action', 'Sci-Fi'],
    director: 'The Wachowskis',
    cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
    setting: 'Virtual reality world',
    plot: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
  },
  {
    name: "Schindler's List",
    genre: ['Biography', 'Drama', 'History'],
    director: 'Steven Spielberg',
    cast: ['Liam Neeson', 'Ben Kingsley', 'Ralph Fiennes'],
    setting: 'Poland, World War II',
    plot: 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
  },
  {
    name: 'Goodfellas',
    genre: ['Biography', 'Crime', 'Drama'],
    director: 'Martin Scorsese',
    cast: ['Robert De Niro', 'Ray Liotta', 'Joe Pesci'],
    setting: 'New York City, 1960s-80s',
    plot: 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.',
  },
  {
    name: 'The Lord of the Rings: The Return of the King',
    genre: ['Action', 'Adventure', 'Drama'],
    director: 'Peter Jackson',
    cast: ['Elijah Wood', 'Viggo Mortensen', 'Ian McKellen'],
    setting: 'Middle-earth',
    plot: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
  },
  {
    name: 'Fight Club',
    genre: ['Drama'],
    director: 'David Fincher',
    cast: ['Brad Pitt', 'Edward Norton', 'Helena Bonham Carter'],
    setting: 'United States',
    plot: 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.',
  },
  {
    name: 'The Silence of the Lambs',
    genre: ['Crime', 'Drama', 'Thriller'],
    director: 'Jonathan Demme',
    cast: ['Jodie Foster', 'Anthony Hopkins', 'Scott Glenn'],
    setting: 'United States',
    plot: 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.',
  },
  {
    name: 'The Departed',
    genre: ['Crime', 'Drama', 'Thriller'],
    director: 'Martin Scorsese',
    cast: ['Leonardo DiCaprio', 'Matt Damon', 'Jack Nicholson'],
    setting: 'Boston',
    plot: 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.',
  },
  {
    name: 'Gladiator',
    genre: ['Action', 'Adventure', 'Drama'],
    director: 'Ridley Scott',
    cast: ['Russell Crowe', 'Joaquin Phoenix', 'Connie Nielsen'],
    setting: 'Roman Empire',
    plot: 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
  },
  {
    name: 'The Green Mile',
    genre: ['Crime', 'Drama', 'Fantasy'],
    director: 'Frank Darabont',
    cast: ['Tom Hanks', 'Michael Clarke Duncan', 'David Morse'],
    setting: 'Louisiana, 1930s',
    plot: 'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.',
  },
  {
    name: 'The Prestige',
    genre: ['Drama', 'Mystery', 'Sci-Fi'],
    director: 'Christopher Nolan',
    cast: ['Hugh Jackman', 'Christian Bale', 'Scarlett Johansson'],
    setting: 'London, 19th century',
    plot: 'After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.',
  },
  {
    name: 'The Shining',
    genre: ['Drama', 'Horror'],
    director: 'Stanley Kubrick',
    cast: ['Jack Nicholson', 'Shelley Duvall', 'Danny Lloyd'],
    setting: 'Colorado, 1980s',
    plot: 'A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from the past and future.',
  },
  {
    name: 'The Social Network',
    genre: ['Biography', 'Drama'],
    director: 'David Fincher',
    cast: ['Jesse Eisenberg', 'Andrew Garfield', 'Justin Timberlake'],
    setting: 'United States',
    plot: 'As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by the twins who claimed he stole their idea.',
  },
  {
    name: 'The Lion King',
    genre: ['Animation', 'Adventure', 'Drama'],
    director: 'Roger Allers, Rob Minkoff',
    cast: ['Matthew Broderick', 'Jeremy Irons', 'James Earl Jones'],
    setting: 'African savanna',
    plot: 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.',
  },
  {
    name: 'Jurassic Park',
    genre: ['Adventure', 'Sci-Fi'],
    director: 'Steven Spielberg',
    cast: ['Sam Neill', 'Laura Dern', 'Jeff Goldblum'],
    setting: 'Isla Nublar',
    plot: 'During a preview tour, a theme park suffers a major power breakdown that allows its cloned dinosaur exhibits to run amok.',
  },
  {
    name: 'The Avengers',
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    director: 'Joss Whedon',
    cast: ['Robert Downey Jr.', 'Chris Evans', 'Scarlett Johansson'],
    setting: 'Various locations',
    plot: "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.",
  },
  {
    name: 'The Wizard of Oz',
    genre: ['Adventure', 'Family', 'Fantasy'],
    director: 'Victor Fleming',
    cast: ['Judy Garland', 'Frank Morgan', 'Ray Bolger'],
    setting: 'Land of Oz',
    plot: 'Dorothy Gale is swept away from a farm in Kansas to a magical land of Oz in a tornado and embarks on a quest with her new friends to see the Wizard who can help her return home.',
  },
  {
    name: 'E.T. the Extra-Terrestrial',
    genre: ['Family', 'Sci-Fi'],
    director: 'Steven Spielberg',
    cast: ['Henry Thomas', 'Drew Barrymore', 'Dee Wallace'],
    setting: 'California',
    plot: 'A troubled child summons the courage to help a friendly alien escape Earth and return to his home world.',
  },
  {
    name: 'The Sound of Music',
    genre: ['Biography', 'Drama', 'Family'],
    director: 'Robert Wise',
    cast: ['Julie Andrews', 'Christopher Plummer', 'Eleanor Parker'],
    setting: 'Austria, 1930s',
    plot: 'A woman leaves an Austrian convent to become a governess to the children of a Naval officer widower.',
  },
  {
    name: 'Gone with the Wind',
    genre: ['Drama', 'History', 'Romance'],
    director: 'Victor Fleming',
    cast: ['Clark Gable', 'Vivien Leigh', 'Leslie Howard'],
    setting: 'Georgia, 1860s-70s',
    plot: 'A manipulative woman and a roguish man conduct a turbulent romance during the American Civil War and Reconstruction periods.',
  },
  {
    name: 'Casablanca',
    genre: ['Drama', 'Romance', 'War'],
    director: 'Michael Curtiz',
    cast: ['Humphrey Bogart', 'Ingrid Bergman', 'Paul Henreid'],
    setting: 'Casablanca, Morocco',
    plot: 'A cynical American expatriate encounters a former lover, with unforeseen complications.',
  },
  {
    name: 'The Great Gatsby',
    genre: ['Drama', 'Romance'],
    director: 'Baz Luhrmann',
    cast: ['Leonardo DiCaprio', 'Carey Mulligan', 'Tobey Maguire'],
    setting: 'Long Island, 1920s',
    plot: 'A writer and wall street trader, Nick, finds himself drawn to the past and lifestyle of his millionaire neighbor, Jay Gatsby.',
  },
  {
    name: 'The Breakfast Club',
    genre: ['Comedy', 'Drama'],
    director: 'John Hughes',
    cast: ['Emilio Estevez', 'Judd Nelson', 'Molly Ringwald'],
    setting: 'Shermer High School',
    plot: 'Five high school students meet in Saturday detention and discover how they have a lot more in common than they thought.',
  },
  {
    name: 'The Sixth Sense',
    genre: ['Drama', 'Mystery', 'Thriller'],
    director: 'M. Night Shyamalan',
    cast: ['Bruce Willis', 'Haley Joel Osment', 'Toni Collette'],
    setting: 'Philadelphia',
    plot: 'A boy who communicates with spirits seeks the help of a disheartened child psychologist.',
  },
  {
    name: 'The Exorcist',
    genre: ['Horror'],
    director: 'William Friedkin',
    cast: ['Ellen Burstyn', 'Max von Sydow', 'Linda Blair'],
    setting: 'Washington D.C.',
    plot: 'When a teenage girl is possessed by a mysterious entity, her mother seeks the help of two priests to save her daughter.',
  },
  {
    name: 'The Terminator',
    genre: ['Action', 'Sci-Fi'],
    director: 'James Cameron',
    cast: ['Arnold Schwarzenegger', 'Linda Hamilton', 'Michael Biehn'],
    setting: 'Los Angeles, 1984',
    plot: "A human soldier is sent from 2029 to 1984 to stop an almost indestructible cyborg killing machine, sent from the same year, which has been programmed to execute a young woman whose unborn son is the key to humanity's future salvation.",
  },
  {
    name: 'The Godfather Part II',
    genre: ['Crime', 'Drama'],
    director: 'Francis Ford Coppola',
    cast: ['Al Pacino', 'Robert De Niro', 'Robert Duvall'],
    setting: 'New York City, Cuba, 1950s-60s',
    plot: 'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.',
  },
  {
    name: 'The Dark Knight Rises',
    genre: ['Action', 'Thriller'],
    director: 'Christopher Nolan',
    cast: ['Christian Bale', 'Tom Hardy', 'Anne Hathaway'],
    setting: 'Gotham City',
    plot: "Eight years after the Joker's reign of anarchy, Batman, with the help of the enigmatic Catwoman, is forced from his exile to save Gotham City from the brutal guerrilla terrorist Bane.",
  },
  {
    name: 'The Revenant',
    genre: ['Adventure', 'Drama', 'Thriller'],
    director: 'Alejandro González Iñárritu',
    cast: ['Leonardo DiCaprio', 'Tom Hardy', 'Domhnall Gleeson'],
    setting: 'American wilderness, 1820s',
    plot: 'A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.',
  },
  {
    name: 'The Lion King',
    genre: ['Animation', 'Adventure', 'Drama'],
    director: 'Roger Allers, Rob Minkoff',
    cast: ['Matthew Broderick', 'Jeremy Irons', 'James Earl Jones'],
    setting: 'African savanna',
    plot: 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.',
  },
  {
    name: 'Jurassic Park',
    genre: ['Adventure', 'Sci-Fi'],
    director: 'Steven Spielberg',
    cast: ['Sam Neill', 'Laura Dern', 'Jeff Goldblum'],
    setting: 'Isla Nublar',
    plot: 'During a preview tour, a theme park suffers a major power breakdown that allows its cloned dinosaur exhibits to run amok.',
  },
  {
    name: 'The Avengers',
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    director: 'Joss Whedon',
    cast: ['Robert Downey Jr.', 'Chris Evans', 'Scarlett Johansson'],
    setting: 'Various locations',
    plot: "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.",
  },
];
